### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by TC-mSundaram** [maheshsundaram/notes#2]
```tsx
import React from "react";
import "./App.css";

function App() {
  return (
    <div className="container">
      <div className="content">
        <div className="sidebar">
          <ul>
            <li>item</li>
          </ul>
        </div>
        <div className="main">
          <div className="main-item">
            <span>content</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
```

```css
#root {
  position: fixed;
  width: 100vw;
  height: 100vh;
}

.container {
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
}

.content {
  display: flex;
  flex-direction: row;
  height: 100%;
  width: 100%;
}

.sidebar {
  flex: 0 0 350px;
  height: 100%;
  overflow: hidden;
}

.sidebar:active,
.sidebar:focus,
.sidebar:hover {
  overflow: auto;
}

.main {
  display: flex;
  flex: 1 0 auto;
  flex-direction: column;
  overflow: auto;
}

.main-item {
  margin: 1rem;
  background-color: blue;
}
```
